---
title: "Master's Project"
author: "Swopnil Adhikari"
date: "2025-02-10"
output: 
  html_document:
    df_print: paged
---

**Library Code**

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(enrichR)
library(lme4)
library(utils)
```

**Load CSV**

```{r}
genes <- read.csv("Literature Data.csv")
```

**Enrichment Code**

```{r}
setEnrichrSite("Enrichr")
autosomal_genes <- c(genes$auto_gene)
enrichr_library <- c("GO_Biological_Process_2023")
enriched_autosmal <- enrichr(autosomal_genes, enrichr_library)
```

**Info Analysis Code**

```{r}
head(autosomal_genes)
write.csv(enriched_autosmal[["GO_Biological_Process_2023"]], "BP Enriched Data V1.02.csv", row.names = FALSE)
```

**Enrichment Data Organization**

```{r}
enriched_autosmal <- as.data.frame(enriched_autosmal)
colnames(enriched_autosmal)[colnames(enriched_autosmal) == "GO_Biological_Process_2023.Genes"] <- "gene_name" 
colnames(enriched_autosmal)[colnames(enriched_autosmal) == "GO_Biological_Process_2023.Term"] <- "process"
```

**Analysis Set Up of Copy Number**

```{r}
count_data <- genes %>%
  select(y_gene, species, y_gene_copy_num, y_gf, enrichment) %>%
  filter(!is.na(y_gene_copy_num)) %>%
  mutate(y_gene_copy_num = as.numeric(y_gene_copy_num))%>%
  arrange(y_gene_copy_num)
head(count_data)
```

**Bar Graph**

```{r}
ggplot(count_data, aes(x = species, y = y_gene_copy_num, fill = y_gene)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    title = "Autosomal Derived Y-Linked Gene Copy Numbers Across Species",
    x = "Species",
    y = "Total Copies",
    fill = "Gene"
  ) +
  theme(
    axis.text.x = element_text(size = 12, angle = 45, hjust = 1),  # Rotate species labels
    axis.text.y = element_text(size = 12),
    plot.title = element_text(size = 10, face = "bold")
  ) +
  scale_fill_viridis_d()

```

**Next Steps**

```{r}
#Linear model is not accurate because copy number is occurrences. LMM assumes graduality whereas copy number is not continuous. So GLMER and Poisson. No Lmer -> GLM. Copy number follows random. I'll finish my data collection and then create a presentation for what I'm testing, why and what we’re expecting. 


```